version: '3'
services:
  gnatsd:
    image: "apcera/gnatsd"
    expose:
     - 4222
     - 6222
     - 8222
    ports:
     - "4222:4222"
     - "6222:6222"
     - "8222:8222"
    # command: "-DV" # debug mode
  proto:
    build: 'proto/.'
    volumes:
      - ./proto:/opt
  api:
    build: 'pub-api/.'
    expose:
     - 3000
    ports:
     - "3000:3000"
    links:
     - gnatsd
    volumes:
     - ./pub-api:/code
     - ./proto/:/code/proto
  nodejs-consumer:
    build: 'pri-nodejs/.'
    links:
     - gnatsd
    environment:
      NATS_URL: "nats://ruser:T0pS3cr3t@gnatsd:4222"
    volumes:
     - ./pri-nodejs:/code
     - ./proto/:/code/proto
  ruby-consumer:
    build: 'pri-ruby/.'
    tty: true
    links:
     - gnatsd
    environment:
      NATS_URL: "nats://ruser:T0pS3cr3t@gnatsd:4222"
    volumes:
     - ./pri-ruby:/code
     - ./proto/:/code/proto

volumes:
  proto:
