# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "nats", "~> 0.8.2"
gem "google-protobuf", "~> 3.4"
gem "rake", "~> 12.1"

group :development do
  gem "filewatcher", "~> 1.0"
  gem "pry-byebug", "~> 3.5"
end
